const MAX_TXT = 255;
const MAGIC_ZMSG = "zmsg:";
const MAGIC_ZMSG_LENGTH = MAGIC_ZMSG.length;
const MAGIC_ZOOKO = "zooko:";
const MAGIC_ZOOKO_LENGTH = MAGIC_ZOOKO.length;
const POST_PAGE_LIMIT = 50;
const ZMSG_START = 102262;

module.exports = {
  MAX_TXT: MAX_TXT,
  MAGIC_ZMSG: MAGIC_ZMSG,
  MAGIC_ZMSG_LENGTH: MAGIC_ZMSG_LENGTH,
  MAGIC_ZOOKO: MAGIC_ZOOKO,
  MAGIC_ZOOKO_LENGTH: MAGIC_ZOOKO_LENGTH,
  POST_PAGE_LIMIT: POST_PAGE_LIMIT,
  ZMSG_START: ZMSG_START
};
